spring.jpa:
  hibernate.ddl-auto: none
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

spring.datasource:
  url: jdbc:postgresql://localhost:5432/annual_leave
  username: postgres
  password: postgres


server:
  port: 8082

jwt:
  secret: secret
  clockSkew: 10
  validFor: 36000